/**
 * Build script to create a modular injected script
 * This script combines all helper modules into a single JavaScript file
 * that can be injected into web pages without module dependencies
 */

const fs = require('fs');
const path = require('path');

// Helper function to read and process TypeScript files
function readHelperFile(filePath) {
    const content = fs.readFileSync(filePath, 'utf8');
    
    // Remove TypeScript imports/exports and interface declarations
    let processed = content
        .replace(/import\s+.*?from\s+.*?;/g, '') // Remove imports
        .replace(/export\s+.*?;/g, '') // Remove exports
        .replace(/declare\s+const\s+.*?;/g, '') // Remove declare statements
        .replace(/interface\s+\w+\s*{[^}]*}/g, '') // Remove interface declarations
        .replace(/\/\*\*[\s\S]*?\*\//g, '') // Remove JSDoc comments
        .replace(/:\s*any\b/g, '') // Remove any types
        .replace(/:\s*number\b/g, '') // Remove number types
        .replace(/:\s*string\b/g, '') // Remove string types
        .replace(/:\s*boolean\b/g, '') // Remove boolean types
        .replace(/:\s*void\b/g, '') // Remove void types
        .replace(/:\s*Promise<[^>]*>/g, '') // Remove Promise types
        .replace(/:\s*Set<[^>]*>/g, '') // Remove Set types
        .replace(/:\s*\w+\[\]/g, '') // Remove array types
        .replace(/:\s*\w+(?=\s*[=,\)\{])/g, '') // Remove other simple types (more precise)
        .replace(/^\s*[\r\n]/gm, '') // Remove empty lines
        .trim();
    
    return processed;
}

// Read all helper files
const helpersDir = path.join(__dirname, 'src', 'helpers');
const helperFiles = [
    'serialization.ts',
    'fiber-utils.ts', 
    'throttling.ts',
    'messaging.ts',
    'fiber-traversal.ts'
];

console.log('📦 Building modular injected script...');

// Combine all helper functions
let combinedHelpers = '';
helperFiles.forEach(file => {
    const filePath = path.join(helpersDir, file);
    if (fs.existsSync(filePath)) {
        console.log(`  ✅ Processing ${file}`);
        combinedHelpers += `\n// === ${file.toUpperCase()} ===\n`;
        combinedHelpers += readHelperFile(filePath);
        combinedHelpers += '\n';
    } else {
        console.warn(`  ⚠️  File not found: ${file}`);
    }
});

// Read the main injected script
const mainScriptPath = path.join(__dirname, 'src', 'injected-modular.ts');
let mainScript = fs.readFileSync(mainScriptPath, 'utf8');

// Remove imports and TypeScript declarations from main script
mainScript = mainScript
    .replace(/import\s+.*?;/g, '') // Remove imports
    .replace(/declare\s+const\s+.*?;/g, '') // Remove declare statements
    .replace(/\/\*\*[\s\S]*?\*\//g, '') // Remove JSDoc comments
    .replace(/:\s*void\b/g, '') // Remove void return types
    .replace(/:\s*any\b/g, '') // Remove any types
    .replace(/:\s*number\b/g, '') // Remove number types
    .replace(/:\s*string\b/g, '') // Remove string types
    .replace(/:\s*boolean\b/g, '') // Remove boolean types
    .replace(/:\s*Promise<[^>]*>/g, '') // Remove Promise types
    .replace(/^\s*[\r\n]/gm, '') // Remove empty lines
    .trim();

// Combine everything
const finalScript = `// React Insight - Modular Injected Script (Auto-generated)
// This file is automatically generated from modular TypeScript sources

${combinedHelpers}

// === MAIN SCRIPT ===
${mainScript}`;

// Write the combined script
const outputPath = path.join(__dirname, 'src', 'injected-combined.js');
fs.writeFileSync(outputPath, finalScript);

console.log(`✅ Modular script built successfully: ${outputPath}`);
console.log(`📊 Total size: ${Math.round(finalScript.length / 1024)}KB`);